services:
  mysql:
    image: mysql:8.4
    container_name: mysql_foodtech
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodtech
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_foodtech
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/foodtech
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
volumes:
  mysql_data:
